spring:
    resources:
        chain:
            strategy:
                content:
                    enabled: true
                    paths: /**
    thymeleaf:
        cache: false
        encoding: UTF-8
        mode: HTML5
        prefix: classpath:/templates/
        suffix: .html
    application:
      name: sport
    datasource:
       druid:
            type: com.alibaba.druid.pool.DruidDataSource
            driver-class-name: com.mysql.jdbc.Driver
            url: jdbc:mysql://47.92.50.180:3306/sport?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
            username: root
            password: root

            # 初始化连接大小
            initial-size: 5
            # 最小空闲连接数
            min-idle: 5
            max-active: 20
            max-wait: 30000
            # 可关闭的空闲连接间隔时间
            time-between-eviction-runs-millis: 60000
            # 配置连接在池中的最小生存时间
            min-evictable-idle-time-millis: 300000
            validation-query: select '1' from dual
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            # 打开PSCache，并且指定每个连接上PSCache的大小
            pool-prepared-statements: true
            max-open-prepared-statements: 20
            max-pool-prepared-statement-per-connection-size: 20
            # 配置监控统计拦截的filters
            filters: stat

            stat-view-servlet:
              url-pattern: /druid/*
              reset-enable: false
              login-username: admin
              login-password: 123456

            web-stat-filter:
              url-pattern: /*
              exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
    redis:
      host: 47.92.50.180
      port: 6379
      lettuce:
        pool:
          max-active: 8
          max-wait: 2000
          max-idle: 8
          min-idle: 8
    rabbitmq:
      host: 47.92.50.180
      port: 5672
      username: guest
      password: guest
server:
  port: 8888
login:
  auth:
    path: /login
mybatis:
  configuration:
    cache-enabled: true
  type-aliases-package: cn.bin2.sport.common.domain
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    cn.bin2.common.mapper: debug
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: cn.bin2.sport.common.domain
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 0
    logic-not-delete-value: 1
    #自定义SQL注入器
    #sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.xxx
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false