spring:
    resources:
        chain:
            strategy:
                content:
                    enabled: true
                    paths: /**
    thymeleaf:
        cache: false
        encoding: UTF-8
        mode: HTML5
        prefix: classpath:/templates/
        suffix: .html
    application:
      name: sport
    datasource:
       druid:
            type: com.alibaba.druid.pool.DruidDataSource
            driverClassName: com.mysql.jdbc.Driver
            url: jdbc:mysql://47.92.50.180:3306/sport?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
            username: root
            password: root

            # 初始化连接大小
            initial-size: 5
            # 最小空闲连接数
            min-idle: 5
            max-active: 20
            max-wait: 30000
            # 可关闭的空闲连接间隔时间
            time-between-eviction-runs-millis: 60000
            # 配置连接在池中的最小生存时间
            min-evictable-idle-time-millis: 300000
            validation-query: select '1' from dual
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            # 打开PSCache，并且指定每个连接上PSCache的大小
            pool-prepared-statements: true
            max-open-prepared-statements: 20
            max-pool-prepared-statement-per-connection-size: 20
            # 配置监控统计拦截的filters
            filters: stat

            stat-view-servlet:
              url-pattern: /druid/*
              reset-enable: false
              login-username: admin
              login-password: 123456

            web-stat-filter:
              url-pattern: /*
              exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
server:
  port: 8888

login:
  auth:
    path: /login